export const AnimalList = [
    { value: 1, label: 'Dog' },
    { value: 2, label: 'Cat' },
    { value: 3, label: 'Cow' },
    { value: 4, label: 'Horse' },
    // { value: 5, label: 'Pig' },
    { value: 6, label: 'Sheep' },
    { value: 7, label: 'Chicken' },
    // { value: 8, label: 'Goat' },
    // { value: 9, label: 'Duck' },
    { value: 10, label: 'Rabbit' },

    // Add more animals here
    // Now adding rolesOptions
    { value: 31, label: "Social Work" },
    { value: 32, label: "Animal Rescue" },
    { value: 33, label: "Environmental Conservation" },
    { value: 34, label: "Education" },
    { value: 35, label: "Healthcare Support" },
    { value: 36, label: "Community Development" },
    { value: 37, label: "Disaster Relief" },
    { value: 38, label: "Youth Mentorship" },
    { value: 39, label: "Elderly Care" },
    { value: 40, label: "Homelessness Outreach" },
    { value: 41, label: "Food Distribution" },
    { value: 42, label: "Housing Assistance" },
    { value: 43, label: "Job Training" },
    { value: 44, label: "Legal Aid" },
    { value: 45, label: "Mental Health Services" },
    { value: 46, label: "Pet Behaviour Speaciallist" },
    { value: 47, label: "Pet Grooming" },
    { value: 48, label: "Pet Training" },
    { value: 49, label: "Pet Walking" },
    { value: 50, label: "Pet Foster Care" },
    { value: 51, label: "Pet Adoption" },
    { value: 52, label: "Pet Health Care" },
    { value: 53, label: "Pet Food Distribution" },
    { value: 54, label: "Pet Shelter Support" },
    { value: 55, label: "Pet Transportation" },
    { value: 56, label: "Pet Volunteer Coordination" },
    { value: 57, label: "Pet Fundraising" },
    { value: 58, label: "Pet Social Media Management" },
    { value: 59, label: "Pet Photography" },
    { value: 60, label: "Pet Videography" },
    { value: 61, label: "Pet Graphic Design" },
    { value: 62, label: "Pet Web Development" },
    { value: 63, label: "Pet App Development" },
    { value: 64, label: "Pet Writing" },
    // Add more roles as needed
];
