export const rolesOptions = [
    { id: 1, name: "Social Work" },
    { id: 2, name: "Animal Rescue" },
    { id: 3, name: "Environmental Conservation" },
    { id: 4, name: "Education" },
    { id: 5, name: "Healthcare Support" },
    { id: 6, name: "Community Development" },
    { id: 7, name: "Disaster Relief" },
    { id: 8, name: "Youth Mentorship" },
    { id: 9, name: "Elderly Care" },
    { id: 10, name: "Homelessness Outreach" },
    { id: 11, name: "Food Distribution" },
    { id: 12, name: "Housing Assistance" },
    { id: 13, name: "Job Training" },
    { id: 14, name: "Legal Aid" },
    { id: 15, name: "Mental Health Services" },
    { id: 16, name: "Pet Behaviour Speaciallist" },
    { id: 17, name: "Pet Grooming" },
    { id: 18, name: "Pet Training" },
    { id: 19, name: "Pet Walking" },
    { id: 21, name: "Pet Foster Care" },
    { id: 22, name: "Pet Adoption" },
    { id: 23, name: "Pet Health Care" },
    { id: 24, name: "Pet Food Distribution" },
    { id: 26, name: "Pet Shelter Support" },
    { id: 27, name: "Pet Transportation" },
    { id: 28, name: "Pet Volunteer Coordination" },
    { id: 29, name: "Pet Fundraising" },
    { id: 31, name: "Pet Social Media Management" },
    { id: 32, name: "Pet Photography" },
    { id: 33, name: "Pet Videography" },
    { id: 34, name: "Pet Graphic Design" },
    { id: 35, name: "Pet Web Development" },
    { id: 36, name: "Pet App Development" },
    { id: 39, name: "Pet Writing" },
    
    // Add more roles as needed
];
